version: '3.4'
services:
  main:
    image: kitsuyui/dynamic-ip-tools:latest@sha256:1e64c19c81040bf9bbe72b8b68d8d7fa55818f47d599d8e5ce9eedb6df500f3c
    # build: .
    env_file:
      - .env
    restart: always
