version: '3.4'
services:
  main:
    image: kitsuyui/dynamic-ip-tools:latest@sha256:765c05591f82866b9f8a40ee47d753253b05c8788ee9d82e268988b6ba931e13
    # build: .
    env_file:
      - .env
    restart: always
