version: '3.4'
services:
  main:
    image: kitsuyui/dynamic-ip-tools:latest@sha256:a7282abdc4788c12e301792c956a79c11465b3a1bd504424ab94282c74a9455a
    # build: .
    env_file:
      - .env
    restart: always
