version: '3.4'
services:
  main:
    image: kitsuyui/dynamic-ip-tools:latest@sha256:7cd710ae57aaa31b138801dfffb22cec454c7b3cd383dea6847e6873b31b55a4
    # build: .
    env_file:
      - .env
    restart: always
