version: '3.4'
services:
  main:
    image: kitsuyui/dynamic-ip-tools:latest@sha256:b69fccff5c49ea55e92fd1345692d4777d70ed93fa55c66e0eb2d0c3801fffaa
    # build: .
    env_file:
      - .env
    restart: always
